version: '2.4'
services:

  backuppc-app:
    image: tiredofit/backuppc
    container_name: backuppc-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.backuppc.rule=Host(`backuppc.example.com`)
      - traefik.http.services.backuppc.loadbalancer.server.port=80
    volumes:
      - ./data:/var/lib/backuppc
      - ./conf/etc/:/etc/backuppc
      - ./conf/home/:/home/backuppc
      - ./logs:/www/logs
    environment:
      - CONTAINER_NAME=backuppc-app
      - USER_BACKUPPC=1000
      - GROUP_BACKUPPC=1000

      - NGINX_AUTHENTICATION_TYPE=BASIC
      - NGINX_AUTHENTICATION_BASIC_USER1=backuppc
      - NGINX_AUTHENTICATION_BASIC_PASS1=backuppc
      - DEBUG_MODE=FALSE
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
